# Custom configuration variables
app:
  base-url: https://localhost  # Base URL without port
  port: 8443 # Standard HTTPS port and 3001 for HTTP
  path: /accounting-software
keycloak:
  base-url: http://localhost:8080
  realm: customer
auth0:
  domain: https://dev-qdejy8uzphouw6cj.us.auth0.com
  client-id: JfT2zq4V575wqYTr8nJljnOLH496kPeC  # Replace with your actual Auth0 client IDauth0:

spring:
  application:
    name: keycloak-with-auth0-idp
  security:
    oauth2:
      client:
        registration:
          keycloak: # <-- This is your registration ID
            client-id: accounting-app
            client-secret: BTZkfBjSGXmGhqK2Ann8PqMpC1IsUXPy
            scope: openid,profile,email,offline_access
            authorization-grant-type: authorization_code
            redirect-uri: ${app.base-url}:${app.port}${app.path}/login/oauth2/code/keycloak # <-- The default redirect URI template in Spring Security is:
            # {baseUrl}/login/oauth2/code/{registrationId}
            # Valid redirect URIs in keycloak must be: http://localhost:3001/login/oauth2/code/*
            client-name: accounting-app
        provider:
          keycloak:
            issuer-uri: ${keycloak.base-url}/realms/${keycloak.realm}
            authorization-uri: ${keycloak.base-url}/realms/${keycloak.realm}/protocol/openid-connect/auth
            token-uri: ${keycloak.base-url}/realms/${keycloak.realm}/protocol/openid-connect/token
            user-info-uri: ${keycloak.base-url}/realms/${keycloak.realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${keycloak.base-url}/realms/${keycloak.realm}/protocol/openid-connect/certs

server:
  port: ${app.port}
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: Password
    key-store-type: PKCS12
    key-alias: myapp
  servlet:
    context-path: ${app.path}